service: business-logic

plugins:
  - serverless-latest-layer-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'} # current stage dev/test/prod
  region: ${opt:region, 'eu-central-1'} / current AWS Region

functions:
  helloWorld:
    handler: handler.hello
    events:
      - http:
          path: helloWorld
          method: get
          cors: true
    environment:
      NODE_PATH: "./:/opt/node_modules" # Important otherwise node_modules imported can not be found
    layers:
      - arn:aws:lambda:eu-central-1:122161723528:layer:dev-base-layer:latest #replace this with arn from layer, or create terraform variable with layer ARN
