service: business-logic

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

functions:
  helloWorld:
    handler: handler.hello
    events:
      - http:
          path: helloWorld
          method: get
          cors: true
