service: business-logic

provider:
  name: aws
  runtime: nodejs10.x # programming language & version
  stage: ${opt:stage, 'dev'} # current stage dev/test/prod
  region: ${opt:region, 'eu-central-1'} # current AWS Region

functions:
  helloWorld:
    handler: handler.hello
    events:
      - http:
          path: helloWorld
          method: get
          cors: true


